baseURL = 'https://sashanaz.github.io/portfolio/'
languageCode = 'en-us'
title = "Sasha Nazareth's CV"
theme = 'm10c'


[params]
  author = "Sasha Nazareth"
  description = "Exploring this amazing world of Data Science"
  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    url = "https://github.com/sashanaz"
  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    url = "https://www.linkedin.com/in/sasha-nazareth-7454301b1/"